### ISSUE TITLE
Add envelope to the language

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/eppEditor#14]

**Comment by sensestage** [comment]
This seems not to be ready yet.

**Comment by sensestage** [comment]
(I'm also pushing some changes to get closer to a working envelope).

The tricky thing is that an adsr envelope goes through the Attack and Decay phases while the trigger is 1, and then stays at the Sustain level. Then it waits for the trigger to go to 0 to go through the release state.
So we need to feed in the trigger value.
That means that we also need a generator that creates a one time pulse with a certain length.

**Comment by sensestage** [comment]
my latest push gets a working envelope.
```
{{{2}sqr,10,400,0.5,500}env,{600}sin}mul
```

**Comment by frantic0** [comment]
Still in progress

**Comment by sensestage** [comment]
fixed with pull request #20
